version: "2"

services:
    postgres:
        image: postgres:9.6.3
        environment:
            - POSTGRES_USER=devel
            - POSTGRES_PASSWORD=123456
            - POSTGRES_DB=bank-reader

    splash:
        image: scrapinghub/splash:3.0
        ports:
            - "8050:8050"
        restart: on-failure

    django:
        build:
            context: ../
            dockerfile: containers/Dockerfile
        env_file: ../.env
        volumes:
            - ..:/app
        ports:
            - "8000:8000"

