require('babel-polyfill');
require('../../node_modules/pikaday/scss/pikaday.scss');
require('../css/main.scss');
require('./client.js');
require('./datepicker.js');
require('./form-controller.js');
require('./processors.js');
require('./bubble-chart-controller.js');
require('./bar-chart-controller.js');
